export const itemsData = [
  {
    id: 1,
    title: "Arne Jacobsen Egg Chair blue",
    price: "220.00",
    salePrice: "199.00",
    image: "/imgs/arne_jacobsen_egg_chair_blue_1_medium.avif",
  },
  {
    id: 2,
    title: "Attractive round chair on low revolving base",
    price: "80.00",
    salePrice: null,
    image: "/imgs/attractive_round_chair_on_low_revolving_base_1_medium.avif",
  },
  {
    id: 3,
    title: "Avenue Six Roundabout Spring Green Lo...",
    price: "78.00",
    salePrice: null,
    image: "/imgs/avenue_six_roundabout_spring_green_low_circle_lounger_1_medium.avif",
  },
  {
    id: 4,
    title: "Camilla Armchair",
    price: "469.00",
    salePrice: null,
    image: "/imgs/camilla_armchair_1_medium.avif",
  },
  {
    id: 5,
    title: "Le Corbusier Armchair",
    price: "399.00",
    salePrice: "500.00",
    image: "/imgs/le_corbusier_armchair_1_medium.avif",
  },
  {
    id: 6,
    title: "Le Corbusier LC7 Chair furniture",
    price: "420.00",
    salePrice: null,
    image: "/imgs/le_corbusier_lc7_chair_furniture_1_medium.avif",
  },
  {
    id: 7,
    title: "Mesa Modern Round Dining Table",
    price: "265.00",
    salePrice: null,
    image: "/imgs/mesa_modern_round_dining_table_1_medium.avif",
  },
  {
    id: 8,
    title: "Miss K Table Lamp by Flos",
    price: "170.00",
    salePrice: null,
    image: "/imgs/miss_k_table_lamp_by_flos_1_medium.avif",
  },
  {
    id: 9,
    title: "Modern Contemporary Self Storage Furniture",
    price: "320.00",
    salePrice: "400.00",
    image: "/imgs/modern_contemporary_self_storage_furniture_hipster_by_zuo_modern_1_medium.avif",
  },
  {
    id: 10,
    title: "Oksana Dining Table",
    price: "199.00",
    salePrice: null,
    image: "/imgs/oksana_dining_table_1_medium.avif",
  },
  {
    id: 11,
    title: "PK20 Easy Chair by Designer Poul Kjærholm for Fritz Hansen",
    price: "60.00",
    salePrice: null,
    image: "/imgs/pk20_easy_chair_by_designer_poul_kjaerholm_for_fritz_hansen_1_medium.avif",
  },
]
